### YamlMime:ManagedReference
items:
- uid: NMF.AnyText.ActionInfoApplication
  commentId: T:NMF.AnyText.ActionInfoApplication
  id: ActionInfoApplication
  parent: NMF.AnyText
  children:
  - NMF.AnyText.ActionInfoApplication.#ctor(NMF.AnyText.CodeActionInfo,NMF.AnyText.Rules.RuleApplication)
  - NMF.AnyText.ActionInfoApplication.Action
  - NMF.AnyText.ActionInfoApplication.RuleApplication
  langs:
  - csharp
  - vb
  name: ActionInfoApplication
  nameWithType: ActionInfoApplication
  fullName: NMF.AnyText.ActionInfoApplication
  type: Struct
  source:
    remote:
      path: AnyText/AnyText.Core/ActionInfoApplication.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: ActionInfoApplication
    path: src/AnyText/AnyText.Core/ActionInfoApplication.cs
    startLine: 14
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText
  summary: Denotes an Action applied at a rule application
  example: []
  syntax:
    content: 'public record struct ActionInfoApplication : IEquatable<ActionInfoApplication>'
    content.vb: Public Structure ActionInfoApplication Implements IEquatable(Of ActionInfoApplication)
  implements:
  - System.IEquatable{NMF.AnyText.ActionInfoApplication}
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: NMF.AnyText.ActionInfoApplication.#ctor(NMF.AnyText.CodeActionInfo,NMF.AnyText.Rules.RuleApplication)
  commentId: M:NMF.AnyText.ActionInfoApplication.#ctor(NMF.AnyText.CodeActionInfo,NMF.AnyText.Rules.RuleApplication)
  id: '#ctor(NMF.AnyText.CodeActionInfo,NMF.AnyText.Rules.RuleApplication)'
  parent: NMF.AnyText.ActionInfoApplication
  langs:
  - csharp
  - vb
  name: ActionInfoApplication(CodeActionInfo, RuleApplication)
  nameWithType: ActionInfoApplication.ActionInfoApplication(CodeActionInfo, RuleApplication)
  fullName: NMF.AnyText.ActionInfoApplication.ActionInfoApplication(NMF.AnyText.CodeActionInfo, NMF.AnyText.Rules.RuleApplication)
  type: Constructor
  source:
    remote:
      path: AnyText/AnyText.Core/ActionInfoApplication.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: .ctor
    path: src/AnyText/AnyText.Core/ActionInfoApplication.cs
    startLine: 14
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText
  summary: Denotes an Action applied at a rule application
  example: []
  syntax:
    content: public ActionInfoApplication(CodeActionInfo Action, RuleApplication RuleApplication)
    parameters:
    - id: Action
      type: NMF.AnyText.CodeActionInfo
      description: the action that is applied
    - id: RuleApplication
      type: NMF.AnyText.Rules.RuleApplication
      description: the rule application that is applied
    content.vb: Public Sub New(Action As CodeActionInfo, RuleApplication As RuleApplication)
  overload: NMF.AnyText.ActionInfoApplication.#ctor*
  nameWithType.vb: ActionInfoApplication.New(CodeActionInfo, RuleApplication)
  fullName.vb: NMF.AnyText.ActionInfoApplication.New(NMF.AnyText.CodeActionInfo, NMF.AnyText.Rules.RuleApplication)
  name.vb: New(CodeActionInfo, RuleApplication)
- uid: NMF.AnyText.ActionInfoApplication.Action
  commentId: P:NMF.AnyText.ActionInfoApplication.Action
  id: Action
  parent: NMF.AnyText.ActionInfoApplication
  langs:
  - csharp
  - vb
  name: Action
  nameWithType: ActionInfoApplication.Action
  fullName: NMF.AnyText.ActionInfoApplication.Action
  type: Property
  source:
    remote:
      path: AnyText/AnyText.Core/ActionInfoApplication.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: Action
    path: src/AnyText/AnyText.Core/ActionInfoApplication.cs
    startLine: 14
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText
  summary: the action that is applied
  example: []
  syntax:
    content: public CodeActionInfo Action { readonly get; set; }
    parameters: []
    return:
      type: NMF.AnyText.CodeActionInfo
    content.vb: Public Property Action As CodeActionInfo
  overload: NMF.AnyText.ActionInfoApplication.Action*
- uid: NMF.AnyText.ActionInfoApplication.RuleApplication
  commentId: P:NMF.AnyText.ActionInfoApplication.RuleApplication
  id: RuleApplication
  parent: NMF.AnyText.ActionInfoApplication
  langs:
  - csharp
  - vb
  name: RuleApplication
  nameWithType: ActionInfoApplication.RuleApplication
  fullName: NMF.AnyText.ActionInfoApplication.RuleApplication
  type: Property
  source:
    remote:
      path: AnyText/AnyText.Core/ActionInfoApplication.cs
      branch: main
      repo: https://github.com/NMFCode/NMF.git
    id: RuleApplication
    path: src/AnyText/AnyText.Core/ActionInfoApplication.cs
    startLine: 14
  assemblies:
  - NMF.AnyText.Core
  namespace: NMF.AnyText
  summary: the rule application that is applied
  example: []
  syntax:
    content: public RuleApplication RuleApplication { readonly get; set; }
    parameters: []
    return:
      type: NMF.AnyText.Rules.RuleApplication
    content.vb: Public Property RuleApplication As RuleApplication
  overload: NMF.AnyText.ActionInfoApplication.RuleApplication*
references:
- uid: NMF.AnyText
  commentId: N:NMF.AnyText
  href: NMF.html
  name: NMF.AnyText
  nameWithType: NMF.AnyText
  fullName: NMF.AnyText
  spec.csharp:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.AnyText
    name: AnyText
    href: NMF.AnyText.html
  spec.vb:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.AnyText
    name: AnyText
    href: NMF.AnyText.html
- uid: System.IEquatable{NMF.AnyText.ActionInfoApplication}
  commentId: T:System.IEquatable{NMF.AnyText.ActionInfoApplication}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<ActionInfoApplication>
  nameWithType: IEquatable<ActionInfoApplication>
  fullName: System.IEquatable<NMF.AnyText.ActionInfoApplication>
  nameWithType.vb: IEquatable(Of ActionInfoApplication)
  fullName.vb: System.IEquatable(Of NMF.AnyText.ActionInfoApplication)
  name.vb: IEquatable(Of ActionInfoApplication)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: NMF.AnyText.ActionInfoApplication
    name: ActionInfoApplication
    href: NMF.AnyText.ActionInfoApplication.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: NMF.AnyText.ActionInfoApplication
    name: ActionInfoApplication
    href: NMF.AnyText.ActionInfoApplication.html
  - name: )
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: NMF.AnyText.ActionInfoApplication.#ctor*
  commentId: Overload:NMF.AnyText.ActionInfoApplication.#ctor
  href: NMF.AnyText.ActionInfoApplication.html#NMF_AnyText_ActionInfoApplication__ctor_NMF_AnyText_CodeActionInfo_NMF_AnyText_Rules_RuleApplication_
  name: ActionInfoApplication
  nameWithType: ActionInfoApplication.ActionInfoApplication
  fullName: NMF.AnyText.ActionInfoApplication.ActionInfoApplication
  nameWithType.vb: ActionInfoApplication.New
  fullName.vb: NMF.AnyText.ActionInfoApplication.New
  name.vb: New
- uid: NMF.AnyText.CodeActionInfo
  commentId: T:NMF.AnyText.CodeActionInfo
  parent: NMF.AnyText
  href: NMF.AnyText.CodeActionInfo.html
  name: CodeActionInfo
  nameWithType: CodeActionInfo
  fullName: NMF.AnyText.CodeActionInfo
- uid: NMF.AnyText.Rules.RuleApplication
  commentId: T:NMF.AnyText.Rules.RuleApplication
  parent: NMF.AnyText.Rules
  href: NMF.AnyText.Rules.RuleApplication.html
  name: RuleApplication
  nameWithType: RuleApplication
  fullName: NMF.AnyText.Rules.RuleApplication
- uid: NMF.AnyText.Rules
  commentId: N:NMF.AnyText.Rules
  href: NMF.html
  name: NMF.AnyText.Rules
  nameWithType: NMF.AnyText.Rules
  fullName: NMF.AnyText.Rules
  spec.csharp:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.AnyText
    name: AnyText
    href: NMF.AnyText.html
  - name: .
  - uid: NMF.AnyText.Rules
    name: Rules
    href: NMF.AnyText.Rules.html
  spec.vb:
  - uid: NMF
    name: NMF
    href: NMF.html
  - name: .
  - uid: NMF.AnyText
    name: AnyText
    href: NMF.AnyText.html
  - name: .
  - uid: NMF.AnyText.Rules
    name: Rules
    href: NMF.AnyText.Rules.html
- uid: NMF.AnyText.ActionInfoApplication.Action*
  commentId: Overload:NMF.AnyText.ActionInfoApplication.Action
  href: NMF.AnyText.ActionInfoApplication.html#NMF_AnyText_ActionInfoApplication_Action
  name: Action
  nameWithType: ActionInfoApplication.Action
  fullName: NMF.AnyText.ActionInfoApplication.Action
- uid: NMF.AnyText.ActionInfoApplication.RuleApplication*
  commentId: Overload:NMF.AnyText.ActionInfoApplication.RuleApplication
  href: NMF.AnyText.ActionInfoApplication.html#NMF_AnyText_ActionInfoApplication_RuleApplication
  name: RuleApplication
  nameWithType: ActionInfoApplication.RuleApplication
  fullName: NMF.AnyText.ActionInfoApplication.RuleApplication
